#!/bin/sh
#
# @name Generic Quadcopter
#
# @type Quadrotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 feed-through of RC AUX1 channel
# @output MAIN6 feed-through of RC AUX2 channel
#
# @output AUX1 feed-through of RC AUX1 channel
# @output AUX2 feed-through of RC AUX2 channel
# @output AUX3 feed-through of RC AUX3 channel
# @output AUX4 feed-through of RC FLAPS channel
#
# @maintainer Lorenz Meier <lorenz@px4.io>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.15
param set-default CA_ROTOR0_PY 0.15
param set-default CA_ROTOR1_PX -0.15
param set-default CA_ROTOR1_PY -0.15
param set-default CA_ROTOR2_PX 0.15
param set-default CA_ROTOR2_PY -0.15
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.15
param set-default CA_ROTOR3_PY 0.15
param set-default CA_ROTOR3_KM -0.05


mavlink start -d /dev/ttyS2 -b 921600
mavlink stream -d /dev/ttyS2 -s ACTUATOR_CONTROL_TARGET -r 0
mavlink stream -d /dev/ttyS2 -s ATTITUDE_TARGET -r 0
mavlink stream -d /dev/ttyS2 -s HIGHRES_IMU -r 0
mavlink stream -d /dev/ttyS2 -s ODOMETRY -r 0
mavlink stream -d /dev/ttyS2 -s SCALED_IMU -r 0
mavlink stream -d /dev/ttyS2 -s SCALED_IMU2 -r 0
mavlink stream -d /dev/ttyS2 -s SCALED_IMU3 -r 0
mavlink stream -d /dev/ttyS2 -s SERVO_OUTPUT_RAW -r 0
mavlink stream -d /dev/ttyS2 -s TIMESYNC -r 0
mavlink stream -d /dev/ttyS2 -s VFR_HUD -r 0
mavlink stream -d /dev/ttyS2 -s ATTITUDE -r 1000
mavlink stream -d /dev/ttyS2 -s LOCAL_POSITION_NED -r 1000






